name: CI

on:
  pull_request:
    branches: ["**"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-ci-env

  check-types:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-ci-env
      - run: pnpm -r type-check

  check-formatting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-ci-env
      - run: pnpm format-check

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-ci-env
      - run: pnpm -r lint-check

  audit-deps:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review')
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-ci-env
      - run: pnpm audit-check
